name: Deploy to Development

on:
  push:
    branches:
    - master
env:
  DB_NAME: ${{ secrets.MYSQL_DBNAME }}
  DB_USER: ${{ secrets.MYSQL_USERNAME }}
  DB_PASS: ${{ secrets.MYSQL_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Update Credentials
      run: |
        echo "Updating MYSQL_DBNAME placeholder"
        sed -i 's/voter_basic/'"$DB_NAME"'/g' src/config/database.php
        echo "Updating MYSQL_USERNAME placeholder"
        sed -i 's/root/'"$DB_USER"'/g' src/config/database.php
        echo "Updating MYSQL_PASSWORD placeholder"
        sed -i 's/password/'"$DB_PASS"'/g' src/config/database.php

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        local-dir: './src/'
        server-dir: './domains/vote.ianbrown.id.au/public_html/'
        server: ${{ secrets.ftp_hostname }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}